"""
report_generator.py
===================
Report Generator  –  synthesises all collected summaries into a polished
Markdown research report and saves it to the `reports/` folder.

The report includes:
  - Title and date
  - Executive summary
  - Key findings (by topic)
  - Source reference cards with clickable links and snippets
  - Conclusion

Events emitted:
  {"type": "report_start"}
  (report_done is emitted by agent.py after save_report completes)
"""

import os
import re
from datetime import datetime

import config
from llm_client import ask_llm


def generate_report(
    question: str,
    summarized_sources: list[dict],
    on_event=None,
) -> str:
    """
    Generate a full Markdown research report from summarized sources.

    Args:
        question:           The original research question.
        summarized_sources: List of dicts with 'url', 'title', 'snippet', 'summary'.
        on_event:           Optional event callback.

    Returns:
        The Markdown report as a string.
    """
    _emit(on_event, {"type": "log", "message": "Building report prompt …"})

    # Build a combined context from all summaries
    source_text = ""
    for i, src in enumerate(summarized_sources, 1):
        source_text += (
            f"\n### Source {i}: {src['title']}\n"
            f"URL: {src['url']}\n"
            f"{src['summary']}\n"
        )

    prompt = f"""You are an expert research writer. Using the source summaries below,
write a comprehensive Markdown research report to answer the research question.

RESEARCH QUESTION: {question}

SOURCE SUMMARIES:
{source_text}

Write the report in this exact Markdown structure:

## Executive Summary
(2-3 sentence overview of the answer)

## Key Findings

### [Finding Category 1]
(detailed paragraphs with facts)

### [Finding Category 2]
(detailed paragraphs with facts)

(add more sections as needed)

## Conclusion
(1-2 paragraphs wrapping up the answer)

Rules:
- Use plain, beginner-friendly language.
- Be factual — only use information from the sources provided.
- Do NOT invent statistics or facts.
- Do NOT include a title or references section — those will be added automatically.
"""
    body = ask_llm(prompt).strip()

    # ── Assemble the full report ───────────────────────────────────────────────
    now        = datetime.now().strftime("%Y-%m-%d %H:%M")
    references = _build_references(summarized_sources)

    report = f"""# Research Report: {question}

*Generated by Research Assistant on {now}*

---

{body}

---

## References & Sources

{references}
"""
    return report


def save_report(question: str, report_markdown: str) -> str:
    """
    Save the Markdown report to the `reports/` directory.

    The filename is derived from the question (spaces → underscores, lowercase)
    with a timestamp suffix to avoid overwriting previous reports.

    Args:
        question:        The research question (used to name the file).
        report_markdown: The full Markdown string to save.

    Returns:
        The absolute path of the saved file.
    """
    os.makedirs(config.REPORTS_DIR, exist_ok=True)

    # Build a safe filename
    safe_name = re.sub(r"[^\w\s-]", "", question.lower())
    safe_name = re.sub(r"\s+", "_", safe_name.strip())[:60]
    timestamp  = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename   = f"{safe_name}_{timestamp}.md"
    filepath   = os.path.join(config.REPORTS_DIR, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report_markdown)

    return os.path.abspath(filepath)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _build_references(sources: list[dict]) -> str:
    """
    Format a rich Markdown reference list.

    Each entry includes the source number, a clickable title link,
    and the DuckDuckGo snippet (or first 150 chars of the summary)
    as a brief description below the link.
    """
    lines = []
    for i, src in enumerate(sources, 1):
        title   = src.get("title",   "Untitled")
        url     = src.get("url",     "#")
        snippet = src.get("snippet", "")
        if not snippet:
            # Fall back to first part of summary, strip bullet markers
            snippet = src.get("summary", "")
            snippet = re.sub(r"^\s*[-•]\s*", "", snippet, flags=re.MULTILINE)
        description = snippet[:180].strip()
        if description and not description.endswith((".", "…")):
            description += " …"

        lines.append(
            f"{i}. **[{title}]({url})**\n"
            f"   *{description}*\n"
        )
    return "\n".join(lines)


def _emit(on_event, event: dict) -> None:
    if on_event is not None:
        try:
            on_event(event)
        except Exception:
            pass
